AudioRecordingFactory#attach_files: fix NoMethodError
```
  3) Importer::Factory::AudioRecordingFactory#cylinder_number with only the md5 for a correct file name
     Failure/Error: f.match(/.*cusb-cyl#{original[1]}b.wav$/)

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/importer/factory/audio_recording_factory.rb:57:in `block in cylinder_number'
     # ./lib/importer/factory/audio_recording_factory.rb:56:in `each'
     # ./lib/importer/factory/audio_recording_factory.rb:56:in `detect'
     # ./lib/importer/factory/audio_recording_factory.rb:56:in `cylinder_number'
     # ./spec/lib/importer/factory/audio_recording_factory_spec.rb:42:in `block (3 levels) in <top (required)>'
     # ./spec/lib/importer/factory/audio_recording_factory_spec.rb:57:in `block (4 levels) in <top (required)>'
```